### ISSUE TITLE
[2.0.x] C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by warbunnies** [MarlinFirmware/Marlin#10370]
I managed to compile marlin 2 with atom & platformio but have not managed to get the lcd sd card working. The best I've gotten is that "#define SD_DETECT_PIN     P2_13" actually recognizes that the card was inserted but the main menu still says "no sd card". For some reason the normal detect pin did not work. I figured it was just my month old version of marlin 2 cause I have tried every change to the spi_pin.h that I could find and none of them seem to have worked. So I loaded the latest files from github and I got this error:
```
Error: Traceback (most recent call last):
  File "c:\users\dakota~1\platfo~1\penv\lib\site-packages\platformio\__main__.py", line 120, in main
    cli(None, None, None)
  File "c:\users\dakota~1\platfo~1\penv\lib\site-packages\click\core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\dakota~1\platfo~1\penv\lib\site-packages\click\core.py", line 680, in main
    rv = self.invoke(ctx)
  File "c:\users\dakota~1\platfo~1\penv\lib\site-packages\click\core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\dakota~1\platfo~1\penv\lib\site-packages\click\core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\dakota~1\platfo~1\penv\lib\site-packages\click\core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "c:\users\dakota~1\platfo~1\penv\lib\site-packages\click\decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\dakota~1\platfo~1\penv\lib\site-packages\platformio\commands\init.py", line 102, in cli
    pg = ProjectGenerator(project_dir, ide, env_name)
  File "c:\users\dakota~1\platfo~1\penv\lib\site-packages\platformio\ide\projectgenerator.py", line 35, in __init__
    self._gather_tplvars()
  File "c:\users\dakota~1\platfo~1\penv\lib\site-packages\platformio\ide\projectgenerator.py", line 151, in _gather_tplvars
    self._tplvars.update(self.get_project_build_data())
  File "c:\users\dakota~1\platfo~1\penv\lib\site-packages\platformio\ide\projectgenerator.py", line 75, in get_project_build_data
    raise result.exception
IOError: [Errno 2] No such file or directory: 'C:\\Users\\Dakota Pahel-Short\\Documents\\3d_PRinter\\Marlin-RC\\Malin2\\Latest_marlin2\\Marlin-bugfix-2.0.x\\Marlin-bugfix-2.0.x\\.piolibdeps\\_tmp_installing-qxlnx8-package\\TMC26XStepper-c1921b4856a5ef4b659b661b8cb5dd56f3075e57\\documentation\\html\\_t_m_c26_x_stepper_8cpp.html'

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  http://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================
```
Any thoughts??? The old version still compiles just fine.

**Comment by warbunnies** [comment]
Found out the issue with the inability to compile. Had to make the path to the folders shorter. Only had to drop them in my documents folder.
