### ISSUE TITLE
Platform .IO compile errors

### ISSUE THREAD

**Issue by CAP1Sup** [MarlinFirmware/Marlin#11974]
Platform.io gives a weird bug when compiling for Marlin. I have tried compiling in Arduino IDE, and after replacing some of the files with the ones that are attached, the Arduino IDE compiled it fine. However, Platform.io is giving some weird errors in the terminal.

[Configuration_Files.zip](https://github.com/MarlinFirmware/Marlin/files/2431750/Configuration_Files.zip)
[arduino-builder-249.zip](https://github.com/MarlinFirmware/Marlin/files/2431752/arduino-builder-249.zip)

Here is the terminal:
```
> Executing task in folder Marlin-bugfix-2.0.x: C:\Users\xmanp\.platformio\penv\Scripts\platformio.exe run <

Processing megaatmega2560 (platform: atmelavr; board: megaatmega2560; framework: arduino)
--------------------------------------------------------------------------------------------------------------------------------------------------------------
LibraryManager: Installing c1921b4
Downloading  [####################################]  100%
Unpacking  [######------------------------------]   17%
Unpacking...
Error: Traceback (most recent call last):
  File "c:\users\xmanp\.platformio\penv\lib\site-packages\platformio\__main__.py", line 120, in main
    cli(None, None, None)
  File "c:\users\xmanp\.platformio\penv\lib\site-packages\click\core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\xmanp\.platformio\penv\lib\site-packages\click\core.py", line 680, in main
    rv = self.invoke(ctx)
  File "c:\users\xmanp\.platformio\penv\lib\site-packages\click\core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\xmanp\.platformio\penv\lib\site-packages\click\core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\xmanp\.platformio\penv\lib\site-packages\click\core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "c:\users\xmanp\.platformio\penv\lib\site-packages\click\decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\xmanp\.platformio\penv\lib\site-packages\platformio\commands\run.py", line 107, in cli
    result = (envname, ep.process())
  File "c:\users\xmanp\.platformio\penv\lib\site-packages\platformio\commands\run.py", line 205, in process
    result = self._run()
  File "c:\users\xmanp\.platformio\penv\lib\site-packages\platformio\commands\run.py", line 300, in _run
    self.verbose)
  File "c:\users\xmanp\.platformio\penv\lib\site-packages\platformio\commands\run.py", line 323, in _autoinstall_libdeps
    ctx.invoke(cmd_lib_install, libraries=[lib], silent=not verbose)
  File "c:\users\xmanp\.platformio\penv\lib\site-packages\click\core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "c:\users\xmanp\.platformio\penv\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "c:\users\xmanp\.platformio\penv\lib\site-packages\platformio\commands\lib.py", line 103, in lib_install
    library, silent=silent, interactive=interactive, force=force)
  File "c:\users\xmanp\.platformio\penv\lib\site-packages\platformio\managers\lib.py", line 352, in install
    force=force)
  File "c:\users\xmanp\.platformio\penv\lib\site-packages\platformio\managers\package.py", line 718, in install
    name, url, requirements, track=True)
  File "c:\users\xmanp\.platformio\penv\lib\site-packages\platformio\managers\package.py", line 444, in _install_from_url
    self.unpack(dlpath, tmp_dir)
  File "c:\users\xmanp\.platformio\penv\lib\site-packages\platformio\managers\package.py", line 224, in unpack
    return fu.unpack(dest_dir, with_progress=False)
  File "c:\users\xmanp\.platformio\penv\lib\site-packages\platformio\unpacker.py", line 112, in unpack
    self._unpacker.extract_item(item, dest_dir)
  File "c:\users\xmanp\.platformio\penv\lib\site-packages\platformio\unpacker.py", line 38, in extract_item
    self._afo.extract(item, dest_dir)
  File "C:\Python27\Lib\zipfile.py", line 1028, in extract
    return self._extract_member(member, path, pwd)
  File "C:\Python27\Lib\zipfile.py", line 1083, in _extract_member
    file(targetpath, "wb") as target:
IOError: [Errno 2] No such file or directory: 'c:\\Users\\xmanp\\Desktop\\3-D printing\\Anet A8\\Upgrades\\Hardware\\Marlin-bugfix-2.0.x-TEST4\\Marlin-bugfix-2.0.x\\.piolibdeps\\_tmp_installing-w6wmgz-package\\TMC26XStepper-c1921b4856a5ef4b659b661b8cb5dd56f3075e57\\documentation\\html\\_t_m_c26_x_stepper_8cpp_source.html'
```

**Comment by CAP1Sup** [comment]
The discussion for the Arduino fix is here:
https://github.com/olikraus/U8glib_Arduino/issues/9

**Comment by Ludy87** [comment]
This is a problem of PIO

try 

    pio update & pio upgrade

**Comment by CAP1Sup** [comment]
I tried this and it didn't help. Do you have any other suggestions? 
Note: The terminal was a little different.
Processing megaatmega2560 (platform: atmelavr; board: megaatmega2560; framework: arduino)


```
LibraryManager: Installing c1921b4

Downloading...

Unpacking

Unpacking

Unpacking...

Error: Traceback (most recent call last):

  File "c:\users\xmanp\.platformio\penv\lib\site-packages\platformio\__main__.py", line 120, in main

    cli(None, None, None)

  File "c:\users\xmanp\.platformio\penv\lib\site-packages\click\core.py", line 700, in __call__

    return self.main(*args, **kwargs)

  File "c:\users\xmanp\.platformio\penv\lib\site-packages\click\core.py", line 680, in main

    rv = self.invoke(ctx)

  File "c:\users\xmanp\.platformio\penv\lib\site-packages\click\core.py", line 1027, in invoke

    return _process_result(sub_ctx.command.invoke(sub_ctx))

  File "c:\users\xmanp\.platformio\penv\lib\site-packages\click\core.py", line 873, in invoke

    return ctx.invoke(self.callback, **ctx.params)

  File "c:\users\xmanp\.platformio\penv\lib\site-packages\click\core.py", line 508, in invoke

    return callback(*args, **kwargs)

  File "c:\users\xmanp\.platformio\penv\lib\site-packages\click\decorators.py", line 16, in new_func

    return f(get_current_context(), *args, **kwargs)

  File "c:\users\xmanp\.platformio\penv\lib\site-packages\platformio\commands\run.py", line 107, in cli

    result = (envname, ep.process())

  File "c:\users\xmanp\.platformio\penv\lib\site-packages\platformio\commands\run.py", line 205, in process

    result = self._run()

  File "c:\users\xmanp\.platformio\penv\lib\site-packages\platformio\commands\run.py", line 300, in _run

    self.verbose)

  File "c:\users\xmanp\.platformio\penv\lib\site-packages\platformio\commands\run.py", line 323, in _autoinstall_libdeps

    ctx.invoke(cmd_lib_install, libraries=[lib], silent=not verbose)

  File "c:\users\xmanp\.platformio\penv\lib\site-packages\click\core.py", line 508, in invoke

    return callback(*args, **kwargs)

  File "c:\users\xmanp\.platformio\penv\lib\site-packages\click\decorators.py", line 26, in new_func

    return f(get_current_context().obj, *args, **kwargs)

  File "c:\users\xmanp\.platformio\penv\lib\site-packages\platformio\commands\lib.py", line 103, in lib_install

    library, silent=silent, interactive=interactive, force=force)

  File "c:\users\xmanp\.platformio\penv\lib\site-packages\platformio\managers\lib.py", line 352, in install

    force=force)

  File "c:\users\xmanp\.platformio\penv\lib\site-packages\platformio\managers\package.py", line 718, in install

    name, url, requirements, track=True)

  File "c:\users\xmanp\.platformio\penv\lib\site-packages\platformio\managers\package.py", line 444, in _install_from_url

    self.unpack(dlpath, tmp_dir)

  File "c:\users\xmanp\.platformio\penv\lib\site-packages\platformio\managers\package.py", line 224, in unpack

    return fu.unpack(dest_dir, with_progress=False)

  File "c:\users\xmanp\.platformio\penv\lib\site-packages\platformio\unpacker.py", line 112, in unpack

    self._unpacker.extract_item(item, dest_dir)

  File "c:\users\xmanp\.platformio\penv\lib\site-packages\platformio\unpacker.py", line 38, in extract_item

    self._afo.extract(item, dest_dir)

  File "C:\Python27\Lib\zipfile.py", line 1028, in extract

    return self._extract_member(member, path, pwd)

  File "C:\Python27\Lib\zipfile.py", line 1083, in _extract_member

    file(targetpath, "wb") as target:

IOError: [Errno 2] No such file or directory: 'C:\\Users\\xmanp\\Desktop\\3-D printing\\Anet A8\\Upgrades\\Hardware\\Marlin-bugfix-2.0.x-TEST4\\Marlin-bugfix-2.0.x\\.piolibdeps\\_tmp_installing-chuiq7-package\\TMC26XStepper-c1921b4856a5ef4b659b661b8cb5dd56f3075e57\\documentation\\html\\_t_m_c26_x_stepper_8cpp_source.html'

Board name: BOARD_RAMPS_14_EFB
Build type: build
Environment used: megaatmega2560
```

**Comment by thinkyhead** [comment]
You may just want to try a fresh new install of PlatformIO.

**Comment by CAP1Sup** [comment]
I think that the TMC26xx library isn't installing. I have checked the installed libraries, and the TMC26xx library isn't on that list.

**Comment by thinkyhead** [comment]
It's downloading for me. It ends up in the folder `.piolibdeps/c1921b4`.

**Comment by CAP1Sup** [comment]
The issue might be there. Could you post a folder tree with names? That way I could check it with what I have.

**Comment by thinkyhead** [comment]
It seems clearly to be a bug in the PlatformIO unpacker script, so you should really be posting in their forums. https://community.platformio.org/

**Comment by amigoloko** [comment]
> The discussion for the Arduino fix is here:
> [olikraus/U8glib_Arduino#9](https://github.com/olikraus/U8glib_Arduino/issues/9)

move entire directory of the project as near as possible to C:/, or any other removable storage device. it also helps if rename folders for shorter versions

**Comment by thinkyhead** [comment]
@amigoloko — Just use Arduino 1.9 beta for Windows which can handle the longer command line generated by having so many more files.
