### ISSUE TITLE
Compile Error VSC Platformio Marlin 1.1.9 [BUG] (short description)

### ISSUE THREAD

**Issue by mikeww1** [MarlinFirmware/Marlin#14267]
### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by mikeww1** [comment]
I was compiling Marlin 1.1.9 2 months ago with no problems.
I modified my printer and changed several parameters.
In the meantime there were certain updates to VSC and maybe also Platformio.
Now I get the following errors. I have reverted to my former project to make sure that my edits are not the cause, but the error stays. I have no idea how to proceed from here.

```
Executing task: C:\Users\mikew\.platformio\penv\Scripts\platformio.exe run <

Processing megaatmega2560 (platform: atmelavr; board: megaatmega2560; framework: arduino)
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
LibraryManager: Installing dev
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
LibraryManager: Installing id=576 @ 1.1.2
Downloading...
Unpacking  [####################################]  100%
LibraryManager: Installing id=1493
Downloading...
Unpacking  [####################################]  100%
Error: Traceback (most recent call last):
  File "c:\users\mikew\.platformio\penv\lib\site-packages\platformio\__main__.py", line 120, in main
    cli(None, None, None)
  File "c:\users\mikew\.platformio\penv\lib\site-packages\click\core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\mikew\.platformio\penv\lib\site-packages\click\core.py", line 680, in main
    rv = self.invoke(ctx)
  File "c:\users\mikew\.platformio\penv\lib\site-packages\click\core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\mikew\.platformio\penv\lib\site-packages\click\core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\mikew\.platformio\penv\lib\site-packages\click\core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "c:\users\mikew\.platformio\penv\lib\site-packages\click\decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\mikew\.platformio\penv\lib\site-packages\platformio\commands\run.py", line 107, in cli
    result = (envname, ep.process())
  File "c:\users\mikew\.platformio\penv\lib\site-packages\platformio\commands\run.py", line 207, in process
    result = self._run()
  File "c:\users\mikew\.platformio\penv\lib\site-packages\platformio\commands\run.py", line 302, in _run
    self.verbose)
  File "c:\users\mikew\.platformio\penv\lib\site-packages\platformio\commands\run.py", line 325, in _autoinstall_libdeps
    ctx.invoke(cmd_lib_install, libraries=[lib], silent=not verbose)
  File "c:\users\mikew\.platformio\penv\lib\site-packages\click\core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "c:\users\mikew\.platformio\penv\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "c:\users\mikew\.platformio\penv\lib\site-packages\platformio\commands\lib.py", line 103, in lib_install
    library, silent=silent, interactive=interactive, force=force)
  File "c:\users\mikew\.platformio\penv\lib\site-packages\platformio\managers\lib.py", line 352, in install
    force=force)
  File "c:\users\mikew\.platformio\penv\lib\site-packages\platformio\managers\package.py", line 723, in install
    pkg_dir = self._install_from_piorepo(name, requirements)
  File "c:\users\mikew\.platformio\penv\lib\site-packages\platformio\managers\lib.py", line 213, in _install_from_piorepo
    if app.get_setting("enable_ssl") else dl_data['url'], requirements)
  File "c:\users\mikew\.platformio\penv\lib\site-packages\platformio\managers\package.py", line 527, in _install_from_url
    return self._install_from_tmp_dir(_tmp_dir, requirements)
  File "c:\users\mikew\.platformio\penv\lib\site-packages\platformio\managers\package.py", line 592, in _install_from_tmp_dir
    shutil.move(pkg_dir, join(self.package_dir, target_dirname))
  File "c:\users\mikew\.platformio\penv\lib\ntpath.py", line 85, in join
    result_path = result_path + p_path
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf6 in position 16: ordinal not in range(128)

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  https://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================
```

**Comment by mikeww1** [comment]
OK I could solve the problem by deleting the .pio* subdirectories.
