### ISSUE TITLE
[BUG] Print stop with Cura, not with S3D

### ISSUE THREAD

**Issue by Parad0x7** [MarlinFirmware/Marlin#16831]
Hello everyone,
I recently update my Creality Cr-10 with marlin 2.0.x bugfix. It’s connected to Raspi 3B+ with octroprint and juste a Pi cam.
Unfortunately, I have trouble if I want to print a GCODE build from Cura (4.0 / 4.4.1 always same result).
If I try the same part with S3D, everything is OK.

I already isolate usb cable, I have the good power supply, I just have a Pi Camera connected on it.

Here is the log part where the error occurs : 
```
2020-02-11 04:14:12,442 - octoprint.util.comm - ERROR - Unexpected error while reading from serial port
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/util/comm.py", line 2793, in _readline
    ret = self._serial.readline()
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/util/comm.py", line 4932, in readline
    c = self.read(1)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/serial/serialposix.py", line 501, in read
    'device reports readiness to read but returned no data '
SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)
2020-02-11 04:14:12,477 - octoprint.util.comm - ERROR - Please see https://faq.octoprint.org/serialerror for possible reasons of this.
2020-02-11 04:14:12,497 - octoprint.util.comm - INFO - Changing monitoring state from "Printing" to "Offline (Error: SerialException: 'device reports readiness to read but returned no data (device disconnected or multiple access on port?)' @ comm.py:_readline:2793)"
2020-02-11 04:25:20,939 - octoprint.server.heartbeat - INFO - Server heartbeat <3
```

Did I forget to configure something ?

Thanks in advance
Have a good day
Parad0x7

**Comment by thinkyhead** [comment]
> ERROR - Unexpected error while reading from serial port

This is not a bug in Marlin. Be sure to configure OctoPrint to NOT DISCONNECT ON "ERROR."
