### ISSUE TITLE
[BUG] TMC2209 on axis Z of a DELTA fails SENSORLESS_HOMING

### ISSUE THREAD

**Issue by AlexanderAmelkin** [MarlinFirmware/Marlin#17549]
### Bug Description 

When I issue the auto G28 homing command, axes as expected go to the top and hit the limits (successfully detected using `SENSORLESS_HOMING` / StallGuard4 on `TMC2209`). Towers X and Y do that successfully, but tower Z fails to do so, hitting the limit and grinding the belt for an excessive amount of time (I usually hit `RESET` in about a second).

### My Configurations

Board: BigTreeTech SKR Pro v1.1
Drivers: BigTreeTech TMC2209 drivers V1.1
Printer: Rostock 301 (Delta), endstop switches removed
Configs: [Rostock301-Configs-Not-working.tar.gz](https://github.com/MarlinFirmware/Marlin/files/4477970/Rostock301-Configs-Not-working.tar.gz)

### Steps to Reproduce

1. Go to `Motion` menu
2. Select `Auto home`
3. Observe the bug
4. Observe that the endstop LED on the Z axis does not light up with the caret hits the limit

**Expected behavior:**
All towers stop in a reasonably short time after hitting the limits, depending on the set sensitivity, endstop LEDs light up when carets hit the limits.

**Actual behavior:**
Tower Z infinitely (or a lot longer than acceptable) crashes into the top grinding the belt without the endstop LED lighting up.

#### Additional Information

Sometimes it works. No correlation to any actions noted. I previously thought that clearing EEPROM or changing Z_HYBRID_THRESHOLD may help, but they don't.

**Comment by AlexanderAmelkin** [comment]
Oh, forgot to say that for sensorless homing to work on SKR Pro v1.1 for a Delta printer, [this change](https://github.com/AlexanderAmelkin/Marlin/commit/9a35674b5f6c6bbaa98a3e73d3a8112fac4c8336) is required.

**Comment by AlexanderAmelkin** [comment]
Also, I'm using Marlin 2.0.5.3 release.

**Comment by AlexanderAmelkin** [comment]
Investigation details:

The endless bumping on Z limit happens when `do_homing_move()` is called for Z for the first time, when `planner.synchronize()` is called from there. 

Here is the backtrace:
```
#1  0x08034e2c in do_homing_move (axis=axis@entry=Z_AXIS, distance=distance@entry=351, fr_mm_s=fr_mm_s@entry=0) at Marlin/src/module/motion.cpp:1338
#2  0x08034f26 in homeaxis (axis=axis@entry=Z_AXIS) at Marlin/src/module/motion.h:128
#3  0x08033d88 in home_delta () at Marlin/src/module/delta.cpp:273
```

Despite that `tmc_enable_stallguard(stepperZ)` is explicitly called from `start_sensorless_homing_per_axis()` called earlier from `do_homing_move()`, and I have checked that it indeed is called, the stallguard doesn't seem to be enabled for Z at that time as the LED doesn't blink at bump.

Here is the dump produced by a manual call to `tmc_get_registers()` before the very first call to `planner.synchronize()` from `do_homing_move()` for axis Y:

```
		X		Y		Z	
GCONF		0x00:00:00:C0	0x00:00:00:C0	0x00:00:00:00	
IHOLD_IRUN	0x00:0A:19:0C	0x00:0A:19:0C	0x00:0A:19:0C	
GSTAT		0x00:00:00:00	0x00:00:00:00	0x00:00:00:00	
IOIN		0x21:00:00:40	0x21:00:02:40	0x00:00:00:00	
TPOWERDOWN	0x00:00:00:80	0x00:00:00:80	0x00:00:00:80	
TSTEP		0x00:0F:FF:FF	0x00:00:0F:B7	0x00:00:00:00	
TPWMTHRS	0x00:00:00:62	0x00:00:00:62	0x00:00:CD:E4	
TCOOLTHRS							
THIGH								
CHOPCONF	0x14:02:81:03	0x14:02:81:03	0x00:00:00:00	
COOLCONF							
PWMCONF	0xC8:0D:0E:24	0xC8:0D:0E:24	0x00:00:00:00	
PWM_SCALE	0x00:02:00:23	0x01:F9:00:49	0x00:00:00:00	
DRV_STATUS	0xC0:0C:00:00	0x40:19:00:00	0x00:00:00:00
```

and this is the same for axis Z:

```
		X		Y		Z	
GCONF		0x00:00:00:C0	0x00:00:00:C0	0x00:00:00:00	
IHOLD_IRUN	0x00:0A:19:0C	0x00:0A:19:0C	0x00:0A:19:0C	
GSTAT		0x00:00:00:00	0x00:00:00:00	0x00:00:00:00	
IOIN		0x21:00:02:40	0x21:00:00:40	0x00:00:00:00	
TPOWERDOWN	0x00:00:00:80	0x00:00:00:80	0x00:00:00:80	
TSTEP		0x00:0F:FF:FF	0x00:0F:FF:FF	0x00:00:00:00	
TPWMTHRS	0x00:00:00:62	0x00:00:00:62	0x00:00:CD:E4	
TCOOLTHRS							
THIGH								
CHOPCONF	0x14:02:81:03	0x14:02:81:03	0x00:00:00:00	
COOLCONF							
PWMCONF	0xC8:0D:0E:24	0xC8:0D:0E:24	0x00:00:00:00	
PWM_SCALE	0x00:00:00:21	0x00:01:00:21	0x00:00:00:00	
DRV_STATUS	0xC0:0C:00:00	0xC0:0C:00:00	0x00:00:00:00
```
As you can see, configuration for Z looks completely different from that for X and Y.
I think that is the reason because for DELTA all tower steppers must have identical configs.

Digging further.

**Comment by AlexanderAmelkin** [comment]
Ok, the last debug printout gave me a hint. As you can see, the IOIN for stepper Z reads all zeroes while it must have 0x21 in the MSB. I swapped the steppers Y and Z and it all started working. Probably there was some bad contact somewhere.

I'm closing this issue.
