### ISSUE TITLE
[BUG]  Marlin on VS Code Traceback error (Absolute Beginer)

### ISSUE THREAD

**Issue by BrocaHatesVSCode** [MarlinFirmware/Marlin#20329]
Hi, I'm trying to set up Vs Code to compile Marlin. It's also important to mention that I have no idea what I'm doing. I'm just following tutorials online, and I have this error that I can find no solution online. I'm sorry if this is not the right place to post this issue or if this is an easy fix with a solution online could someone direct me to it. As I said I'm a beginner and don't even know what to look for. If what I provided is insufficient please ask for more information, I didn't know what to include.

I've installed Marlin-bugfix-2.0 from the Marlin Github. I then opened the folder in VS Code, the first sign of the trouble was  that both the Configuration.h and Configuration_adv.h files both had Errors in the first line:

`#include errors detected. Please update your includePath. Squiggles are disabled for this translation unit (C:\Users\Monster\Documents\Marlin Firmware\Marlin\src\MarlinCore.cpp).`

Ignoring this error I continued my ill-fated quest,

I then dragged files in the Marlin Configurations-bugfix-2.0.x corresponding to my board (SKR mini E3 V2.0).
Then I went to Auto Marlin Build and tried Auto Build with my Environment (STM32F103RC_btt_512K). When I tried to build it, I first got this message int he Terminal:

   ```
  PS C:\Users\Monster\Documents\Marlin Firmware> platformio run -e STM32F103RC_btt_512K
     Processing STM32F103RC_btt_512K (platform: ststm32@~6.1; board: genericSTM32F103RC; framework: 
     arduino)

```
then after a spilt second the fucking red message:

```
Error: Traceback (most recent call last):
  File "c:\users\monster\.platformio\penv\lib\site-packages\platformio\__main__.py", line 109, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "c:\users\monster\.platformio\penv\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\monster\.platformio\penv\lib\site-packages\click\core.py", line 782, in main   
    rv = self.invoke(ctx)
  File "c:\users\monster\.platformio\penv\lib\site-packages\platformio\commands\__init__.py", line 44, in invoke
    return super(PlatformioCLI, self).invoke(ctx)
  File "c:\users\monster\.platformio\penv\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\monster\.platformio\penv\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\monster\.platformio\penv\lib\site-packages\click\core.py", line 610, in invoke 
    return callback(*args, **kwargs)
  File "c:\users\monster\.platformio\penv\lib\site-packages\click\decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\monster\.platformio\penv\lib\site-packages\platformio\commands\run\command.py", line 143, in cli
    is_test_running,
  File "c:\users\monster\.platformio\penv\lib\site-packages\platformio\commands\run\command.py", line 175, in process_env
    result = {"env": name, "duration": time(), "succeeded": ep.process()}
  File "c:\users\monster\.platformio\penv\lib\site-packages\platformio\commands\run\processor.py", line 79, in process
    result = p.run(build_vars, build_targets, self.silent, self.verbose, self.jobs)
  File "c:\users\monster\.platformio\penv\lib\site-packages\platformio\platform\_run.py", line 60, in run
    self.autoinstall_runtime_packages()
  File "c:\users\monster\.platformio\penv\lib\site-packages\platformio\platform\_packages.py", line 67, in autoinstall_runtime_packages
    if self.get_package(name):
  File "c:\users\monster\.platformio\penv\lib\site-packages\platformio\platform\_packages.py", line 31, in get_package
    return self.pm.get_package(self.get_package_spec(name))
  File "c:\users\monster\.platformio\penv\lib\site-packages\platformio\package\manager\base.py", line 236, in get_package
    for pkg in self.get_installed():
  File "c:\users\monster\.platformio\penv\lib\site-packages\platformio\package\manager\base.py", line 209, in get_installed
    pkg = PackageItem(pkg_dir)
  File "c:\users\monster\.platformio\penv\lib\site-packages\platformio\package\meta.py", line 400, in __init__
    self.metadata = self.load_meta()
  File "c:\users\monster\.platformio\penv\lib\site-packages\platformio\package\meta.py", line 430, in load_meta
    return PackageMetaData.load(manifest_path)
  File "c:\users\monster\.platformio\penv\lib\site-packages\platformio\package\meta.py", line 386, in load
    data = json.load(fp)
  File "C:\Users\Monster\.platformio\python3\lib\json\__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Users\Monster\.platformio\python3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Monster\.platformio\python3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Monster\.platformio\python3\lib\json\decoder.py", line 355, in raw_decode      
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
============================================================

An unexpected error occurred. Further steps:
  `pip install -U platformio` command

(Request help blah blah, Ive removed two messages that gave me links for troubleshooting)

============================================================
PS C:\Users\Monster\Documents\Marlin Firmware> echo "done" >C:\Users\Monster\AppData\Local\Temp\ipc
PS C:\Users\Monster\Documents\Marlin Firmware> 
```

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://forum.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
