### ISSUE TITLE
Fail to compile marlin on btt skr mini e3 v3

### ISSUE THREAD

**Issue by ardiramelan** [MarlinFirmware/Marlin#25047]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Hi guys, im starting to pull my hair now. Whenever i try to build the marlin firmware for skr mini e3 v3 using vs code, i always get this errror

FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\rahardi.kramadibrata\.platformio\.cache\tmp\pkg-installing-5fvbqsuq\Arduino_Core_STM32-main\variants\STM32MP1xx\MP133AA(E-F-G)_MP133CA(E-F-G)_MP133DA(E-F-G)_MP133FA(E-F-G)_MP135AA(E-F-G)_MP135CA(E-F-G)_MP135DA(E-F-G)_MP135FA(E-F-G)\variant_generic.cpp'.

however, when I tried several times using skr mini e3 v2 or any other board such as ANET board it worked. I wonder what is the problem ? any help would be appreciated

### Bug Timeline

1 December 2022

### Expected behavior

 Success build/compile the firmware

### Actual behavior

 Can't build/compile the firmware

### Steps to Reproduce

1. Download and extract Marlin 2.1.1
2. Edit the header file (configuration .h) #define MOTHERBOARD BOARD_BTT_SKR_MINI_E3_V3_0 
3. Edit the platformio.ini default_envs = STM32G0B1RE_btt
4. Build / Compile the firmware

### Version of Marlin Firmware

2.1.1

### Printer model

Creality Ender 3

### Electronics

Bigtreetech SKR Mini E3 V3 

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

`` *  Executing task in folder Marlin-2.1.1: C:\Users\rahardi.kramadibrata\.platformio\penv\Scripts\platformio.exe run 

Processing STM32G0B1RE_btt (platform: ststm32@~14.1.0; board: marlin_STM32G0B1RE; framework: arduino)
--------------------------------------------------------------------------------------------------------------------------------Tool Manager: Installing https://github.com/stm32duino/Arduino_Core_STM32/archive/main.zip
Unpacking  [##################################--]   97%  00:00:00
Unpacking...
Error: Traceback (most recent call last):
  File "C:\Users\rahardi.kramadibrata\.platformio\penv\lib\site-packages\platformio\package\manager\_install.py", line 38, in unpack
    return fu.unpack(dst, with_progress=with_progress)
  File "C:\Users\rahardi.kramadibrata\.platformio\penv\lib\site-packages\platformio\package\unpack.py", line 175, in unpack     
    self._archiver.extract_item(item, dest_dir)
  File "C:\Users\rahardi.kramadibrata\.platformio\penv\lib\site-packages\platformio\package\unpack.py", line 48, in extract_item    self._afo.extract(item, dest_dir)
  File "C:\Users\rahardi.kramadibrata\.platformio\python3\lib\zipfile.py", line 1616, in extract
    return self._extract_member(member, path, pwd)
  File "C:\Users\rahardi.kramadibrata\.platformio\python3\lib\zipfile.py", line 1687, in _extract_member
    open(targetpath, "wb") as target:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\rahardi.kramadibrata\\.platformio\\.cache\\tmp\\pkg-installing-p0hqc3oj\\Arduino_Core_STM32-main\\variants\\STM32MP1xx\\MP133AA(E-F-G)_MP133CA(E-F-G)_MP133DA(E-F-G)_MP133FA(E-F-G)_MP135AA(E-F-G)_MP135CA(E-F-G)_MP135DA(E-F-G)_MP135FA(E-F-G)\\variant_generic.cpp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\rahardi.kramadibrata\.platformio\penv\lib\site-packages\platformio\__main__.py", line 102, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "C:\Users\rahardi.kramadibrata\.platformio\penv\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\rahardi.kramadibrata\.platformio\penv\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\rahardi.kramadibrata\.platformio\penv\lib\site-packages\platformio\cli.py", line 71, in invoke
    return super().invoke(ctx)
  File "C:\Users\rahardi.kramadibrata\.platformio\penv\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\rahardi.kramadibrata\.platformio\penv\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\rahardi.kramadibrata\.platformio\penv\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\rahardi.kramadibrata\.platformio\penv\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\rahardi.kramadibrata\.platformio\penv\lib\site-packages\platformio\run\cli.py", line 144, in cli
    process_env(
  File "C:\Users\rahardi.kramadibrata\.platformio\penv\lib\site-packages\platformio\run\cli.py", line 201, in process_env       
    result = {"env": name, "duration": time(), "succeeded": ep.process()}
  File "C:\Users\rahardi.kramadibrata\.platformio\penv\lib\site-packages\platformio\run\processor.py", line 83, in process      
    install_project_env_dependencies(
  File "C:\Users\rahardi.kramadibrata\.platformio\penv\lib\site-packages\platformio\package\commands\install.py", line 131, in install_project_env_dependencies
    _install_project_env_platform(project_env, options),
  File "C:\Users\rahardi.kramadibrata\.platformio\penv\lib\site-packages\platformio\package\commands\install.py", line 148, in _install_project_env_platform
    PlatformPackageManager().install(
  File "C:\Users\rahardi.kramadibrata\.platformio\penv\lib\site-packages\platformio\package\manager\platform.py", line 62, in install
    p.install_required_packages(force=force)
  File "C:\Users\rahardi.kramadibrata\.platformio\penv\lib\site-packages\platformio\platform\_packages.py", line 76, in install_required_packages
    self.install_package(name, force=force)
  File "C:\Users\rahardi.kramadibrata\.platformio\penv\lib\site-packages\platformio\platform\_packages.py", line 70, in install_package
    return self.pm.install(spec or self.get_package_spec(name), force=force)
  File "C:\Users\rahardi.kramadibrata\.platformio\penv\lib\site-packages\platformio\package\manager\_install.py", line 48, in install
    pkg = self._install(spec, skip_dependencies=skip_dependencies, force=force)
  File "C:\Users\rahardi.kramadibrata\.platformio\penv\lib\site-packages\platformio\package\manager\_install.py", line 98, in _install
    pkg = self.install_from_uri(spec.uri, spec)
  File "C:\Users\rahardi.kramadibrata\.platformio\penv\lib\site-packages\platformio\package\manager\_install.py", line 188, in install_from_uri
    self.unpack(dl_path, tmp_dir)
  File "C:\Users\rahardi.kramadibrata\.platformio\penv\lib\site-packages\platformio\package\manager\_install.py", line 43, in unpack
    return fu.unpack(dst, with_progress=False)
  File "C:\Users\rahardi.kramadibrata\.platformio\penv\lib\site-packages\platformio\package\unpack.py", line 170, in unpack     
    self._archiver.extract_item(item, dest_dir)
  File "C:\Users\rahardi.kramadibrata\.platformio\penv\lib\site-packages\platformio\package\unpack.py", line 48, in extract_item    self._afo.extract(item, dest_dir)
  File "C:\Users\rahardi.kramadibrata\.platformio\python3\lib\zipfile.py", line 1616, in extract
    return self._extract_member(member, path, pwd)
  File "C:\Users\rahardi.kramadibrata\.platformio\python3\lib\zipfile.py", line 1687, in _extract_member
    open(targetpath, "wb") as target:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\rahardi.kramadibrata\\.platformio\\.cache\\tmp\\pkg-installing-p0hqc3oj\\Arduino_Core_STM32-main\\variants\\STM32MP1xx\\MP133AA(E-F-G)_MP133CA(E-F-G)_MP133DA(E-F-G)_MP133FA(E-F-G)_MP135AA(E-F-G)_MP135CA(E-F-G)_MP135DA(E-F-G)_MP135FA(E-F-G)\\variant_generic.cpp'

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  https://docs.platformio.org/page/faq/index.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

 *  The terminal process "C:\Users\rahardi.kramadibrata\.platformio\penv\Scripts\platformio.exe 'run'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it.

**Comment by jmz52** [comment]
Are there non-english characters in your windows username?

**Comment by thisiskeithb** [comment]
Delete your `C:\Users\rahardi.kramadibrata\.platformio\packages` & `C:\Users\rahardi.kramadibrata\.platformio\.cache` folders and let PIO rebuild them.

---

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

**Comment by ardiramelan** [comment]
For anybody who share the same issue, it is because the folder name is too long. The solution is to enable the longpath in the windows32 

see the tutorial here :https://www.thewindowsclub.com/how-to-enable-or-disable-win32-long-paths-in-windows-11-10
