### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'get_debug_tool_name'

### ISSUE THREAD

**Issue by Jonas-Alber** [MarlinFirmware/Marlin#26059]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

No debugging possible with Marlin projects in VSCode.

<details><summary>details:</summary>
<p>

```prolog
AttributeError: Traceback (most recent call last):
  File "C:\Users\uic98235\.platformio\penv\Lib\site-packages\platformio\__main__.py", line 103, in main
    cli()  # pylint: disable=no-value-for-parameter
    ^^^^^
  File "C:\Users\jonas\.platformio\penv\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\.platformio\penv\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\.platformio\penv\Lib\site-packages\platformio\cli.py", line 85, in invoke
    return super().invoke(ctx)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\.platformio\penv\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\.platformio\penv\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\.platformio\penv\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\.platformio\penv\Lib\site-packages\click\decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\.platformio\penv\Lib\site-packages\platformio\debug\cli.py", line 104, in cli
    debug_config = _configure(*configure_args)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\.platformio\penv\Lib\site-packages\platformio\debug\cli.py", line 115, in _configure
    debug_config = DebugConfigFactory.new(
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\.platformio\penv\Lib\site-packages\platformio\debug\config\factory.py", line 34, in new
    board_config.get_debug_tool_name(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'get_debug_tool_name'
```

</p>
</details>

### Bug Timeline

Today

### Expected behavior

Start Debugger

### Steps to Reproduce

Unkown

### Version of Marlin Firmware

2.1.2.1

### Electronics

STM32F407ZET6

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

[Configfiles.zip](https://github.com/MarlinFirmware/Marlin/files/11981742/Configfiles.zip)

### Additional information & file uploads

The problem occurs both in new projects with the current Marlin-bugfix-2.1.x and in existing projects.
According to Platformio Support, the problem is with Marlin.
Testing with a Platformio STM32 setup problem confirms that debugging works in principle. The problem occurs only in Marlin projects.
Error occurs as well with Configuration of other Printers like ANETET4 on a STM32F407VGT6

**Comment by ellensp** [comment]
get_debug_tool_name is part of penv/lib/python3.10/site-packages/platformio/platform/board.py  as provided by platformio

You need to provide way more details.

Ie a step by step to reproduce

**Comment by Jonas-Alber** [comment]
I know too little about Platformio and Marlin to reproduce the error. Since the problem occurs with all Marlin projects I can't refer to a working project.
What I found out so far is that the env_name is simulator_linux_debug and the following is the content of the board_config where the get_debug_tool_name throws its error
```cmd
{'marlin_Artillery_Ruby': <platformio.platform.board.PlatformBoardConfig object at 0x000002E33D804E50>, 'marlin_BTT_SKR_SE_BX': <platformio.platform.board.PlatformBoardConfig object at 0x000002E3408EB510>, 'marlin_BigTree_BTT002': <platformio.platform.board.PlatformBoardConfig object at 0x000002E340545150>, 'marlin_BigTree_BTT002_VET6': <platformio.platform.board.PlatformBoardConfig object at 0x000002E34093B610>, 'marlin_BigTree_GTR_v1': <platformio.platform.board.PlatformBoardConfig object at 0x000002E3409226D0>, 'marlin_BigTree_Octopus_Pro_v1_F429': <platformio.platform.board.PlatformBoardConfig object at 0x000002E340850310>, 'marlin_BigTree_Octopus_v1': <platformio.platform.board.PlatformBoardConfig object at 0x000002E3408C9310>, 'marlin_BigTree_SKR_Pro': <platformio.platform.board.PlatformBoardConfig object at 0x000002E3408C9450>, 'marlin_CREALITY_STM32F401RC': <platformio.platform.board.PlatformBoardConfig object at 0x000002E3408C93D0>, 'marlin_FYSETC_CHEETAH_V20': <platformio.platform.board.PlatformBoardConfig object at 0x000002E3408C9510>, 'marlin_MKS_SKIPR_V1': <platformio.platform.board.PlatformBoardConfig object at 0x000002E340947D90>, 'marlin_STM32F401RC': <platformio.platform.board.PlatformBoardConfig object at 0x000002E340945910>, 'marlin_STM32F407VET6_CCM': <platformio.platform.board.PlatformBoardConfig object at 0x000002E340946310>, 'marlin_STM32F407VGT6_CCM': <platformio.platform.board.PlatformBoardConfig object at 0x000002E340729D50>, 'marlin_STM32F407ZET6': <platformio.platform.board.PlatformBoardConfig object at 0x000002E340944110>, 'marlin_STM32F407ZGT6': <platformio.platform.board.PlatformBoardConfig object at 0x000002E340946E10>, 'marlin_STM32F429VGT6': <platformio.platform.board.PlatformBoardConfig object at 0x000002E340955A10>, 'marlin_STM32F446ZET_tronxy': <platformio.platform.board.PlatformBoardConfig object at 0x000002E340954D50>, 'marlin_STM32G0B1RE': <platformio.platform.board.PlatformBoardConfig object at 0x000002E34095ED50>, 'marlin_STM32H743Vx': <platformio.platform.board.PlatformBoardConfig object at 0x000002E34095F810>, 'marlin_archim': <platformio.platform.board.PlatformBoardConfig object at 0x000002E34095DF10>, 'marlin_blackSTM32F407VET6': <platformio.platform.board.PlatformBoardConfig object at 0x000002E34096AE10>, 'marlin_fysetc_s6': <platformio.platform.board.PlatformBoardConfig object at 0x000002E34096AD50>, 'marlin_maple_CHITU_F103': <platformio.platform.board.PlatformBoardConfig object at 0x000002E34093E590>, 'marlin_maple_MEEB_3DP': <platformio.platform.board.PlatformBoardConfig object at 0x000002E34096B910>, 'marlin_opulo_lumen_rev3': <platformio.platform.board.PlatformBoardConfig object at 0x000002E340970FD0>, 'marlin_opulo_lumen_rev4': <platformio.platform.board.PlatformBoardConfig object at 0x000002E340971E90>}
```
Can you give me instructions on how I could best reproduce the error?

**Comment by ellensp** [comment]
you cannot use this board in the simulator

to use simulator_linux_debug you must set #define MOTHERBOARD BOARD_SIMULATED

**Comment by Jonas-Alber** [comment]
I do not want to use the linux simulator but the specified board.

Until Friday, it had worked with the previous setting. I have now tried to change the simulator_linux_debug to simulator_windows. It did not work. VSCode shows me beside the native.ini no more file in which simulator_linux_debug is contained within the project, nevertheless when running the debugger simulator_linux_debug is output to me as env_name.

**Comment by ellensp** [comment]
then env_name should be set to what your board needs

which is unknown as you have created a custom board.
 all we have is the name BOARD_SCARA_CONTROLLER

**Comment by Jonas-Alber** [comment]
Ok, sorry for wasting your time. I have since found out that I made a mistake configuring the debug settings in VSCode. Apparently the debugger file settings reset to their defaults in development (probably by me) and I didn't realize it.
Thanks a lot for your help.
