### ISSUE TITLE
[BUG] mc-apply script doesn't function

### ISSUE THREAD

**Issue by CRCinAU** [MarlinFirmware/Marlin#27612]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

If `CONFIGURATION_EMBEDDING` is enabled, the `M503 C` command will write `MC.ZIP` to the printers SD card with the compile time settings used.

According to `docs/ConfigEmbedding.md`, the following should be used to then apply that config template back to the .h files:
```
$ git checkout -f
$ unzip mc.zip
$ python buildroot/share/PlatformIO/scripts/mc-apply.py
```

When attempting this, the script always returns:
```
$ python3 ../buildroot/share/PlatformIO/scripts/mc-apply.py 
No marlin_config.json found.
```

Removing the main `try` / `except` block, I get:
```
$ python3 buildroot/share/PlatformIO/scripts/mc-apply.py 
Traceback (most recent call last):
  File "/home/netwiz/git/Marlin/buildroot/share/PlatformIO/scripts/mc-apply.py", line 22, in <module>
    for k, v in sorted(conf[key].items()):
                       ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'items'
```

When adding a debug to see what `key` contains, I see:
```
$ python3 buildroot/share/PlatformIO/scripts/mc-apply.py 
Key: Z_SAFE_HOMING_X_POINT
Traceback (most recent call last):
  File "/home/netwiz/git/Marlin/buildroot/share/PlatformIO/scripts/mc-apply.py", line 23, in <module>
    for k, v in sorted(conf[key].items()):
                       ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'items'
```

As a result, no configuration files are modified and the `marlin_config.json` file cannot be folded back into the configuration.

### Bug Timeline

Likely a while.

### Expected behavior

The script should restore config settings from `marlin_config.json` to the related .h files.

### Actual behavior

Error in output.

### Steps to Reproduce

See main description.

### Version of Marlin Firmware

bugfix-2.1.x

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

Added example `marlin_config.json` as per output of `M503 C`.
[marlin_config.json](https://github.com/user-attachments/files/18268788/marlin_config.json)

**Comment by ellensp** [comment]
in older marlin `CONFIG_EXPORT 1` the file `marlin_config.json` used to start with
```
'{"__INITIAL_HASH":"6c2dd0c6a928862c1c0c","Configuration.h":{"VALIDATE_HOMING_ENDSTOPS" 
```
and the script got `Configuration.h` from here.

now `CONFIG_EXPORT  1` (`marlin_config.json`) starts with
```
{"Z_SAFE_HOMING_X_POINT":"X_CENTER","VALIDATE_HOMING_ENDSTOPS":"","Y_DRIVER_TYPE":"TMC2209","PREHEAT_1_LABEL":"\"PLA\"","EXTRUDE_MAXLENGTH":"600","MPC_STEADYSTATE":"0.5f","TEMP_WINDOW":"1","E
```
`CONFIG_EXPORT 101` adds the filenames back in.

**Comment by ellensp** [comment]
first attempt removed...

**Comment by CRCinAU** [comment]
Yeah, there's still a few cases that this doesn't cover (did it ever?)

1) Configuration_adv.h as noted. Maybe its just better to load both into different string variables and search both for `key`?

Or am I misunderstanding and no values from `Configuration_adv.h` are actually making it into the embedded config? If this is the case, then we probably should look at fixing that too.

2) Values that are added but are not mentioned in any .h file present

There are a bunch of `opt_*` files in `buildroot/bin/` that seem to basically be the shell script equivalents to what `mc-apply.py` would probably need to have for proper functionality - however these are obviously designed to be run individually on a per config option basis.

**Comment by ellensp** [comment]
`--opt` creates `Configuration.h.sh` which contains 

_e.g._,
```
opt_enable ARC_SUPPORT
opt_enable AUTOTEMP
opt_set AUTOTEMP_FACTOR 0.1f
opt_set AUTOTEMP_MAX 250
opt_set AUTOTEMP_MIN 210
opt_set AUTOTEMP_OLDWEIGHT 0.98
```
etc.

**Comment by ellensp** [comment]
I see a light at the end of the tunnel...

In `Configuration_adv.h` is

```
 *  1 = marlin_config.json - Dictionary containing the configuration.
 *      This file is also generated for CONFIGURATION_EMBEDDING.
 *  2 = config.ini - File format for PlatformIO preprocessing.
 *  3 = schema.json - The entire configuration schema. (13 = pattern groups)
 *  4 = schema.yml - The entire configuration schema.
 *  5 = Config.h - Minimal configuration by popular demand.
 */
#define CONFIG_EXPORT 105 // :[1:'JSON', 2:'config.ini', 3:'schema.json', 4:'schema.yml', 5:'Config.h']
```

but the value is > 5
So what gives there ?

The answer is 
```
    # Get the CONFIG_EXPORT value and do an extended dump if > 100
    # For example, CONFIG_EXPORT 102 will make a 'config.ini' with a [config:] group for each schema @section
```

101 processes both `Configuration.h` and `Configuration_adv.h`  and puts the file name in as expected
(and `Version.h`, but thats a little broken) 

## This is a red herring, we are only looking at type 1

**Comment by Ferrograph** [comment]
I tried the new scrip above but it still outputs not found.

```
PS D:\Working\PROJECTS\Marlin\Code> python buildroot/share/PlatformIO/scripts/mc-apply.py 
Error: marlin_config.json not found.
PS D:\Working\PROJECTS\Marlin\Code> 
```

**Comment by ellensp** [comment]
it expects marlin_config.json in the directory you invoke the script from  ie in this case 
 D:\Working\PROJECTS\Marlin\Code\marlin_config.json

But its not complete yet...

**Comment by Ferrograph** [comment]
Ok, Ive tried it in there (the root folder with configs h, and /src. I'll wait for an update.

Thanks for all your hard work.

**Comment by ellensp** [comment]
Moved code updates to pull request https://github.com/MarlinFirmware/Marlin/pull/27628

Note mc-apply.py only works with CONFIG_EXPORT set to 1, as originally intended.

I've tested this lots, apart from some minor formatting issues, which i'm not concerned about. This now seems to work as expected 

Note any extra defines that are not in the stock configs are appended to the end of Configuration.h 

Please give this a try.

**Comment by CRCinAU** [comment]
I'm curious - does `CONFIG_EXPORT 1` also store settings from `Configuration_adv.h`?

I was under the impression that without the extended dump (ie 101), it would only do `Configuration.h` values?

Of course, I could be greatly misunderstanding...

**Comment by ellensp** [comment]
yes 1 contains both set of data. 
101 splits the defines into containers for configure file and section headers 
1 everything is now in a mostly flat json file. (the original version had  containers for each config file)

**Comment by ellensp** [comment]
So thinkyhead goes in the opposite direction, changes marlin so CONFIG_EXPORT 1 has Configuration file containers...

**Comment by CRCinAU** [comment]
I'm confused now - the PR for updating `mc-apply.py` was merged, but also other changes?

Does that mean that `mc-apply.py` needs more changes to work now? Or should it now 'just work'?

**Comment by Ferrograph** [comment]
Im also confused is this fixed with updated documentation or not?

**Comment by thinkyhead** [comment]
> So thinkyhead goes in the opposite direction, changes marlin so CONFIG_EXPORT 1 has Configuration file containers...

Oops! Just found this comment and so I went ahead and quickly patched `signature.py` to fix `CONFIG_EXPORT 1` so it is flat again.
