### ISSUE TITLE
Printer halt and lost connection (reboot?) on retract

### ISSUE THREAD

**Issue by a0s** [MarlinFirmware/Marlin#6436]
Hi! I found a strange bug with 1.1.0-RC8. This bug is not exist with RCBugFix branch f41fb2b6358
It seems like halt and rebooting of board before/during series of retracts. It always appears on first layer after brim. Bugged gcode [gcode.tar.gz](https://github.com/MarlinFirmware/Marlin/files/950527/gcode.tar.gz)

I saw different messages in logs:
Octoprint 1.3.2 + RC8
```
2017-04-22 18:16:33,874 - Recv: ok T:229.9 /230.0 B:110.1 /110.0 @:56 B@:79
2017-04-22 18:16:33,886 - Send: N2295 G0 F2215.4 X97.02 Y74.208*89
2017-04-22 18:16:33,978 - Recv: ok
2017-04-22 18:16:33,983 - Send: N2296 G0 X95.496 Y75.248*28
2017-04-22 18:16:33,992 - Recv: ok
2017-04-22 18:16:33,996 - Send: N2297 G0 X95.518 Y75.286*24
2017-04-22 18:16:34,071 - Recv: ok
2017-04-22 18:16:34,075 - Send: N2298 G1 F2700 E211.71309*63
2017-04-22 18:16:34,249 - Recv: ok
2017-04-22 18:16:34,254 - Send: N2299 G1 F1200 X95.566 Y75.26 E211.71755*11
2017-04-22 18:16:34,266 - Recv: Error:No Line Number with checksum, Last Line: 570444102
2017-04-22 18:16:42,573 - Changing monitoring state from 'Printing' to 'Operational'
2017-04-22 18:17:01,067 - Unexpected error while reading serial port, please consult octoprint.log for details: SerialException: 'device reports readiness to read but returned no data (device disconnected or multiple access on port?)' @ comm.py:_readline:1792
2017-04-22 18:17:01,075 - Changing monitoring state from 'Operational' to 'Offline: SerialException: 'device reports readiness to read but returned no data (device disconnected or multiple access on port?)' @ comm.py:_readline:1792'
2017-04-22 18:17:01,085 - Connection closed, closing down monitor
```

Again Octoprint 1.3.2 + RC8
```
Send: N2292 G1 X97.045 Y74.239*22
Recv: ok
Send: N2293 G1 F2700 E205.71309*49
Recv: ok
Send: N2294 G0 F2215.4 X97.02 Y74.208*88
Recv: ok
Send: N2295 G0 X95.496 Y75.248*31
Recv: ok
Send: N2296 G0 X95.518 Y75.286*25
Recv: ok
Send: the
Recv: Error:Printer halted. kill() called!
Changing monitoring state from 'Printing' to 'Operational'
Send: M400
Unexpected error while reading serial port, please consult octoprint.log for details: SerialException: 'device reports readiness to read but returned no data (device disconnected or multiple access on port?)' @ comm.py:_readline:1792
Changing monitoring state from 'Operational' to 'Offline: SerialException: 'device reports readiness to read but returned no data (device disconnected or multiple access on port?)' @ comm.py:_readline:1792'
Connection closed, closing down monitor
```

Pronterface + RC8
```
RECV: ok
SENT: N2155 G1 X97.045 Y74.239*30
RECV: ok
SENT: N2156 G1 F2700 E205.71309*59
RECV: ok
SENT: N2157 G0 F2215.4 X97.02 Y74.208*84
RECV: ok
SENT: N2158 G0 X95.496 Y75.248*29
RECV: ok
SENT: N2159 G0 X95.518 Y75.286*25
RECV: ok
SENT: N2160 G1 F2700 E211.71309*59
RECV: start
SENT: M105
RECV: echo:Marlin 1.1.0-RC8
RECV: echo: Last Updated: 2016-12-06 12:00 | Author: (none, default config)
RECV: Compiled: Apr 23 2017
RECV: echo: Free Memory: 3999  PlannerBufferBytes: 1168
RECV: echo:Hardcoded Default Settings Loaded
RECV: echo:Steps per unit:
RECV: echo:  M92 X160.00 Y160.00 Z5120.00 E1105.08
RECV: echo:Maximum feedrates (mm/s):
RECV: echo:  M203 X160.00 Y160.00 Z5.00 E50.00
RECV: echo:Maximum Acceleration (mm/s2):
RECV: echo:  M201 X800 Y800 Z100 E5000
RECV: echo:Accelerations: P=printing, R=retract and T=travel
RECV: echo:  M204 P800.00 R5000.00 T800.00
RECV: echo:Advanced variables: S=Min feedrate (mm/s), T=Min travel feedrate (mm/s), B=minimum segment time (ms), X=maximum XY jerk (mm/s),  Z=maximum Z jerk (mm/s),  E=maximum E jerk (mm/s)
RECV: echo:  M205 S0.00 T0.00 B20000 X5.00 Y5.00 Z0.40 E5.00
RECV: echo:Home offset (mm)
RECV: echo:  M206 X0.00 Y0.00 Z0.00
RECV: echo:PID settings:
RECV: echo:  M301 P23.81 I1.11 D127.20
RECV: echo:  M304 P114.45 I10.20 D321.13
RECV: echo:Filament settings: Disabled
RECV: echo:  M200 D3.00
RECV: echo:  M200 D0
RECV: echo:Z-Probe Offset (mm):
RECV: echo:  M851 Z-7.50
RECV: echo:SD card ok
RECV: ok T:0.0 /0.0 B:0.0 /0.0 @:0 B@:0
SENT: N2161 G1 F1200 X95.566 Y75.26 E211.71755*15
RECV: Error:Line Number is not Last Line Number+1, Last Line: 0
[ERROR] Error:Line Number is not Last Line Number+1, Last Line: 0

RECV: Resend: 1
RECV: ok
[ERROR] Print thread died due to the following error:
Traceback (most recent call last):
  File "/Users/craigvanvliet/Desktop/PyInstaller-2.1/pronterface/build/pronterface/out00-PYZ.pyz/printrun.printcore", line 497, in _print
  File "/Users/craigvanvliet/Desktop/PyInstaller-2.1/pronterface/build/pronterface/out00-PYZ.pyz/printrun.printcore", line 533, in _sendnext
KeyError: 1

[ERROR] Printer is currently printing. Please pause the print before you issue manual commands.
Disconnected.
SENT: M105
```

My board is RUMBA
Configuration.h https://pastebin.com/79SWCAmd
Configuration_adv.h https://pastebin.com/zg4WdpYw
pins_RUMBA.h https://pastebin.com/KAeWwNCq

**Comment by thinkyhead** [comment]
> This bug is not exist with `RCBugFix` branch

In that case, I will mark this as solved. Marlin 1.1.0 will be released on Sunday.
