### ISSUE TITLE
Travis CI ImportError "No module named backports.functools_lru_cache"

### ISSUE THREAD

**Issue by thinkyhead** [MarlinFirmware/Marlin#8562]
What could be causing this in our Travis CI testing?
```
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.13/bin/platformio", line 7, in <module>
    from platformio.__main__ import main
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/platformio/__main__.py", line 23, in <module>
    from platformio import __version__, exception, maintenance
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/platformio/maintenance.py", line 25, in <module>
    from platformio.commands.lib import lib_update as cmd_lib_update
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/platformio/commands/lib.py", line 22, in <module>
    import arrow
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/arrow/__init__.py", line 3, in <module>
    from .arrow import Arrow
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/arrow/arrow.py", line 19, in <module>
    from arrow import util, locales, parser, formatter
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/arrow/parser.py", line 12, in <module>
    from backports.functools_lru_cache import lru_cache  # pragma: no cover
ImportError: No module named backports.functools_lru_cache
```

**Comment by Roxy-3D** [comment]
My guess is Travis is broken...   And this problem will go away when they fix it.    But that is just a guess.

Is there an easy way to search other projects on GitHub that use Travis?   Because I bet they are seeing problems too.  Travis is a GitHub project...  Maybe there are issues being opened up there?

**Comment by thinkyhead** [comment]
#8563 seems to fix it, for now.

**Comment by ivankravets** [comment]
Fixed in https://github.com/crsmithdev/arrow/issues/495

Just restart a job.
